version: '3'

services: 
  web:
    build: .
    volumes: 
      - ".:/app"
    working_dir: /app
    ports: 
      - "8080:8080"
    tty: true
    # command: sh -c "cd app && yarn install && yarn serve"

